---
虛擬貨幣分析
=============

```{r setup, include=FALSE}
library(ggplot2)
require(lattice) 
data=read.csv("coin.csv")
#ETHER:https://etherscan.io/chart/etherprice
#BITCOIN:https://www.coindesk.com/price/
#RIPPLE:https://www.coingecko.com/en/price_charts/ripple/usd
x=data$num
y1=data$ether
y2=data$bitcoin
y3=data$ripple
my.df <- data.frame(y1,y2,y3)
library("NLP")
library("tm")
library('RColorBrewer')
library('wordcloud')
```

#擷取2016/01/01到2017/12/20的三個虛擬貨幣資訊 分別是ether,bitcoin,ripple
#將三種貨幣的價格作為折線圖資料(合併)

```{r}
ggplot(my.df, aes(x = x)) +
  geom_line(aes(y = y1)) +
  geom_line(aes(y = y2)) +
  geom_line(aes(y = y3))
```

#因為發現價格差距過大,無法從圖片中看出同時的漲跌狀況,因此改為分開來看



```{r}
xyplot(x=y1~x ,         
       data=data,     
       panel=function(x,y){  
         panel.fill(col="black")        
         panel.xyplot(x, y)             
         panel.lmline(x, y, col="red")  
       }
       
)

xyplot(x=y2~x ,         
       data=data,     
       panel=function(x,y){  
         panel.fill(col="black")        
         panel.xyplot(x, y)             
         panel.lmline(x, y, col="red")  
       }
       
)
xyplot(x=y3~x ,         
       data=data,     
       panel=function(x,y){  
         panel.fill(col="black")        
         panel.xyplot(x, y)             
         panel.lmline(x, y, col="red")  
       }
       
)
```

#從以上3張圖可以清楚看到在400以前幾乎沒有起伏2017/02/03
#因此以下將從400天之後開始分析

```{r}
x1=data$num[c(400:720)]
y4=data$ether[c(400:720)]
y5=data$bitcoin[c(400:720)]
y6=data$ripple[c(400:720)]
my.df2 <- data.frame(y4,y5,y6)



ggplot(my.df2, aes(x = x1)) +
  geom_line(aes(y = y4)) +
  geom_line(aes(y = y5)) +
  geom_line(aes(y = y6))





xyplot(x=y4~x1 ,         
       data=data,     
       panel=function(x,y){  
         panel.fill(col="black")        
         panel.xyplot(x, y)             
         panel.lmline(x, y, col="red")  
       }
       
)

xyplot(x=y5~x1 ,         
       data=data,     
       panel=function(x,y){  
         panel.fill(col="black")        
         panel.xyplot(x, y)             
         panel.lmline(x, y, col="red")  
       }
       
)
xyplot(x=y6~x1 ,         
       data=data,     
       panel=function(x,y){  
         panel.fill(col="black")        
         panel.xyplot(x, y)             
         panel.lmline(x, y, col="red")  
       }
       
)
```
後續發展只有ether持續往上漲,其他2個皆有下滑的趨勢

##蒐集新聞資料
從Factiva.com 道瓊社及路透社新聞資料庫
關鍵字:china；USA；america
2017年
6/27~7/16
9/5~9/14
選擇網路新聞資料

##匯入資料並做成文字雲

```{r}
coin = readLines("remove.txt")
docs = Corpus(VectorSource(coin))
docs <- tm_map(docs, removeWords, stopwords("english"))
a = c("the","com","can","journal","can","morning","china","new","daily","sign","follow","newsletter","good","download","chinese","letter")
docs1<- tm_map(docs, removeWords,a)
docs <- tm_map(docs,removeWords,"shares")
docs <- tm_map(docs,removeWords,"week")
docs <- tm_map(docs,removeWords,"will")
docs <- tm_map(docs,removeWords,"get")
wordcloud(docs1,
          scale=c(5,0.1),min.freq=10,max.words=150,
          random.order=TRUE, random.color=FALSE,
          rot.per=.1, colors=brewer.pal(8, "Dark2"),
          ordered.colors=FALSE,use.r.layout=FALSE,
          fixed.asp=TRUE)
```